/* Flashcards e banco de questoes.
   Flashcard: f = frente (pergunta), v = verso (resposta).
   Questao: q = enunciado, ops = alternativas, certa = indice, porque = explicacao. */

const FLASHCARDS = {

modelagem: [
  { f: 'Quais são os três níveis da modelagem de dados?', v: '<b>Conceitual</b> (DER, sem tecnologia) → <b>Lógico</b> (tabelas e chaves, sem SGBD) → <b>Físico</b> (tipos e índices, já no SGBD escolhido).' },
  { f: 'Em qual nível aparecem as tabelas?', v: 'No <b>lógico</b>. O conceitual tem entidades, não tabelas.' },
  { f: 'Qual nível depende do SGBD escolhido?', v: 'Só o <b>físico</b>.' },
  { f: 'No DER: retângulo, elipse e losango são o quê?', v: 'Retângulo = <b>entidade</b>. Elipse = <b>atributo</b>. Losango = <b>relacionamento</b>.' },
  { f: 'O que é um atributo multivalorado? Pode existir no modelo relacional?', v: 'É o que guarda vários valores para a mesma linha (vários telefones). <b>Não pode</b> no relacional, vira uma tabela nova.' },
  { f: 'O que é um atributo derivado?', v: 'O que é calculado a partir de outro e normalmente <b>não se armazena</b>. Ex: idade, que vem da data de nascimento.' },
  { f: 'Chave primária aceita NULL?', v: '<b>Nunca.</b> Precisa ser única e obrigatória.' },
  { f: 'Chave estrangeira aceita NULL?', v: '<b>Aceita.</b> Significa "ainda não tem relacionamento".' },
  { f: 'Qual a diferença entre chave candidata e alternativa?', v: '<b>Candidata</b> é qualquer coluna que poderia ser PK. <b>Alternativa</b> é a candidata que não foi escolhida.' },
  { f: 'Em um relacionamento 1:N, onde fica a chave estrangeira?', v: '<b>Sempre no lado N.</b> Um curso tem vários alunos → curso_id fica na tabela alunos.' },
  { f: 'Como se implementa um relacionamento N:N?', v: 'Criando uma <b>tabela associativa</b> com as duas chaves estrangeiras. Ela transforma o N:N em dois relacionamentos 1:N.' },
  { f: 'Por que N:N não pode ser resolvido só com FK?', v: 'Porque uma coluna guarda <b>um valor só</b>. Não haveria onde escrever os vários ids sem violar a 1FN.' },
  { f: 'O que costuma aparecer na tabela associativa além das duas FKs?', v: '<b>Atributos do próprio relacionamento</b>: nota, data, quantidade. Dados que não pertencem a nenhuma das duas entidades sozinha.' },
  { f: 'O que é integridade referencial?', v: 'A garantia, feita pela FK, de que não existe referência para uma linha que não existe.' },
  { f: 'O que exige a 1FN?', v: 'Todo campo com <b>um valor só</b> (atômico) e <b>sem grupos repetidos</b> (telefone1, telefone2...).' },
  { f: 'O que exige a 2FN?', v: 'Estar na 1FN e <b>não ter dependência parcial</b>: nenhum campo pode depender só de <i>parte</i> da chave composta.' },
  { f: 'Quando a 2FN pode ser violada?', v: '<b>Só quando a chave primária é composta.</b> Se a PK é uma coluna só, estar em 1FN já garante a 2FN.' },
  { f: 'O que exige a 3FN?', v: 'Estar na 2FN e <b>não ter dependência transitiva</b>: nenhum campo não-chave pode depender de outro campo não-chave.' },
  { f: 'Qual o mantra das três formas normais?', v: 'Cada campo depende <b>da chave</b> (1FN), <b>da chave inteira</b> (2FN) e <b>de nada além da chave</b> (3FN).' },
  { f: 'Quais são as três anomalias que a normalização resolve?', v: 'De <b>inserção</b>, de <b>atualização</b> e de <b>exclusão</b>.' },
  { f: 'O que é uma entidade fraca?', v: 'A que não existe sem outra entidade e tem <b>chave parcial</b>. No DER é desenhada com <b>retângulo duplo</b>. Ex: dependente de funcionário.' },
  { f: 'O que é autorrelacionamento?', v: 'Quando a entidade se relaciona com ela mesma. Ex: funcionário chefia funcionário.' },
  { f: 'Na generalização, o que significa total × parcial?', v: '<b>Total</b>: toda ocorrência da entidade genérica obrigatoriamente pertence a um subtipo. <b>Parcial</b>: pode não pertencer a nenhum.' }
],

sql: [
  { f: 'CREATE, ALTER e DROP pertencem a qual categoria?', v: '<b>DDL</b>: Data Definition Language. Definem a estrutura.' },
  { f: 'INSERT, UPDATE e DELETE pertencem a qual categoria?', v: '<b>DML</b>: Data Manipulation Language. Mexem nos dados.' },
  { f: 'GRANT e REVOKE pertencem a qual categoria?', v: '<b>DCL</b>: Data Control Language. Controlam permissões.' },
  { f: 'COMMIT e ROLLBACK pertencem a qual categoria?', v: '<b>TCL</b>: Transaction Control Language.' },
  { f: 'Qual a diferença entre DELETE e TRUNCATE?', v: '<b>DELETE</b> é DML, apaga linha a linha, aceita WHERE e pode sofrer ROLLBACK. <b>TRUNCATE</b> é DDL, esvazia tudo de uma vez, não aceita WHERE e não dá para desfazer.' },
  { f: 'Qual a diferença entre DROP e TRUNCATE?', v: '<b>DROP</b> apaga a tabela inteira, estrutura junto. <b>TRUNCATE</b> só esvazia, a tabela continua existindo.' },
  { f: 'UNIQUE aceita NULL?', v: '<b>Sim</b>, aceita um NULL. Quem não aceita é a PRIMARY KEY.' },
  { f: 'Qual a diferença entre CHAR e VARCHAR?', v: '<b>CHAR</b> tem tamanho fixo (completa com espaço, mais rápido). <b>VARCHAR</b> é variável (ocupa só o necessário).' },
  { f: 'Por que nunca usar FLOAT para dinheiro?', v: 'Porque é um tipo <b>aproximado</b> e gera erro de arredondamento. Use <b>DECIMAL</b>, que é exato.' },
  { f: 'Qual a ordem correta das cláusulas do UPDATE?', v: '<b>UPDATE</b> tabela <b>SET</b> coluna = valor <b>WHERE</b> condição.' },
  { f: 'O que acontece se você rodar UPDATE ou DELETE sem WHERE?', v: 'O comando vale para <b>todas as linhas da tabela</b>.' },
  { f: 'No LIKE, o que significam % e _ ?', v: '<b>%</b> = qualquer quantidade de caracteres. <b>_</b> = exatamente um caractere.' },
  { f: 'Por que WHERE coluna = NULL não funciona?', v: 'Porque NULL é <b>ausência de valor</b>, não se compara com =. O correto é <b>IS NULL</b> / <b>IS NOT NULL</b>.' },
  { f: 'Qual a diferença entre COUNT(*) e COUNT(coluna)?', v: '<b>COUNT(*)</b> conta todas as linhas. <b>COUNT(coluna)</b> <b>ignora os NULL</b> daquela coluna.' },
  { f: 'Qual a diferença entre WHERE e HAVING?', v: '<b>WHERE filtra linhas, antes de agrupar.</b> <b>HAVING filtra grupos, depois de agrupar.</b> Agregação só pode no HAVING.' },
  { f: 'Qual a regra de ouro do GROUP BY?', v: 'Toda coluna do SELECT que <b>não</b> está dentro de uma função de agregação precisa estar no GROUP BY.' },
  { f: 'Qual a diferença entre INNER JOIN e LEFT JOIN?', v: '<b>INNER</b> traz só o que combina nos dois lados. <b>LEFT</b> traz tudo da esquerda, tendo par ou não (o resto vira NULL).' },
  { f: 'Como listar quem NÃO tem correspondência em outra tabela?', v: '<b>LEFT JOIN</b> + <b>WHERE coluna_da_direita IS NULL</b>.' },
  { f: 'Quantos JOINs são necessários para atravessar um N:N?', v: '<b>Dois</b>: um até a tabela associativa e outro dela até a outra entidade.' },
  { f: 'Qual a ordem lógica de execução de um SELECT?', v: '<b>FROM → JOIN → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT</b>' },
  { f: 'Por que não posso usar um apelido do SELECT dentro do WHERE?', v: 'Porque o <b>WHERE roda antes do SELECT</b>. No ORDER BY funciona, porque ele roda depois.' },
  { f: 'O que faz DISTINCT?', v: 'Elimina <b>linhas repetidas</b> do resultado.' },
  { f: 'BETWEEN 7 AND 9 inclui o 7 e o 9?', v: '<b>Sim, inclui as duas pontas.</b>' },
  { f: 'Se a subconsulta devolve vários valores, uso = ou IN?', v: '<b>IN.</b> Com = o banco dá erro.' }
],

so: [
  { f: 'Qual a diferença fundamental entre processo e thread?', v: 'Processo tem <b>memória própria e isolada</b>. Threads do mesmo processo <b>compartilham a memória</b> dele.' },
  { f: 'O que cada thread tem só dela?', v: '<b>Pilha, registradores e contador de programa.</b> O resto (código, dados, arquivos) é compartilhado.' },
  { f: 'Quais são os cinco estados de um processo?', v: '<b>Novo → Pronto → Executando → Bloqueado → Terminado</b>' },
  { f: 'Um processo bloqueado volta direto para Executando?', v: '<b>Não.</b> Ele volta para <b>Pronto</b> e espera o escalonador chamar. Essa transição é a pegadinha mais comum.' },
  { f: 'O que é preempção?', v: 'O SO <b>tirar a CPU</b> de um processo que ainda não terminou. É a transição Executando → Pronto.' },
  { f: 'O que é o PCB?', v: '<b>Process Control Block</b>: a estrutura com todos os dados do processo, estado, contador de programa, registradores, prioridade, memória, arquivos abertos.' },
  { f: 'O que é troca de contexto e por que ela é ruim?', v: 'Salvar o PCB do processo que sai e carregar o do que entra. É <b>overhead</b>: trabalho puro que não produz nada útil.' },
  { f: 'Qual a desvantagem da thread de usuário?', v: 'Se <b>uma</b> bloqueia, <b>todas bloqueiam</b>: o SO não sabe que elas existem. E não aproveita múltiplos núcleos.' },
  { f: 'Por que a thread de kernel é mais lenta?', v: 'Porque cada operação sobre ela exige uma <b>chamada de sistema</b>.' },
  { f: 'Scheduler e dispatcher: quem faz o quê?', v: '<b>Scheduler escolhe</b> qual processo executa. <b>Dispatcher faz a troca de contexto</b> e entrega a CPU.' },
  { f: 'Qual a fórmula do turnaround?', v: '<b>Turnaround = conclusão − chegada</b>' },
  { f: 'Qual a fórmula do tempo de espera?', v: '<b>Espera = turnaround − tempo de execução</b>' },
  { f: 'Qual o problema do FCFS?', v: 'O <b>efeito comboio</b>: um processo longo na frente atrasa todos os pequenos atrás dele.' },
  { f: 'Qual algoritmo dá o menor tempo médio de espera?', v: '<b>SJF</b>: é matematicamente ótimo. O problema é precisar saber de antemão a duração de cada processo.' },
  { f: 'Qual o problema do SJF e da prioridade? Como resolve?', v: '<b>Starvation</b> (inanição): um processo pode nunca ser escolhido. Resolve-se com <b>aging</b>: a prioridade sobe com o tempo de espera.' },
  { f: 'O que acontece se o quantum do Round Robin for muito grande?', v: 'O RR <b>vira FCFS</b>. Se for muito pequeno, gasta-se mais tempo em troca de contexto do que executando.' },
  { f: 'Quais são as quatro condições de Coffman?', v: '<b>1. Exclusão mútua · 2. Posse e espera · 3. Não preempção · 4. Espera circular.</b> Precisam ocorrer todas ao mesmo tempo.' },
  { f: 'Qual a diferença entre deadlock e starvation?', v: 'No <b>deadlock</b> ninguém do grupo anda, nunca. Na <b>starvation</b> o sistema funciona normalmente, só aquele processo nunca é escolhido.' },
  { f: 'O algoritmo do banqueiro é prevenção ou evitação?', v: '<b>Evitação.</b> Ele analisa cada pedido e só concede se o sistema continuar em <b>estado seguro</b>.' },
  { f: 'O que é o algoritmo do avestruz?', v: '<b>Ignorar</b> o deadlock. É o que Windows e Linux fazem na prática.' },
  { f: 'Mutex × semáforo: qual a diferença principal?', v: '<b>Mutex tem dono</b> (só quem travou destrava) e deixa passar um. <b>Semáforo é um contador</b>, não tem dono e deixa passar N.' },
  { f: 'Quais são as operações do semáforo?', v: '<b>wait</b> (P, down, decrementa) e <b>signal</b> (V, up, incrementa).' },
  { f: 'O que é condição de corrida?', v: 'Duas threads mexem no <b>mesmo dado ao mesmo tempo</b> e o resultado final depende de quem chegou primeiro.' },
  { f: 'O que é região crítica?', v: 'O trecho de código que acessa o <b>recurso compartilhado</b> e precisa de exclusão mútua.' },
  { f: 'Paginação × segmentação: qual gera qual fragmentação?', v: '<b>Paginação</b> = tamanho fixo → fragmentação <b>interna</b>. <b>Segmentação</b> = tamanho variável → fragmentação <b>externa</b>.' },
  { f: 'O que é thrashing?', v: 'Quando o sistema passa <b>mais tempo trocando páginas</b> entre RAM e disco do que efetivamente executando.' },
  { f: 'Qual a organização física do HD?', v: '<b>Pratos → trilhas → setores → cilindros.</b> O setor é a menor unidade física.' },
  { f: 'Interrupção × trap: qual a diferença?', v: '<b>Interrupção</b> vem do <b>hardware</b> (dispositivo avisando). <b>Trap</b> vem do <b>software</b> (divisão por zero, chamada de sistema).' },
  { f: 'O que é DMA?', v: 'Transferência <b>direta</b> entre dispositivo e memória, sem passar pela CPU. Ela só é avisada no fim.' }
],

seguranca: [
  { f: 'Quais são os três princípios do tripé da segurança?', v: '<b>Confidencialidade, Integridade e Disponibilidade</b> (CID).' },
  { f: 'Um site derrubado por DDoS viola qual princípio?', v: '<b>Disponibilidade.</b>' },
  { f: 'Um boleto adulterado viola qual princípio?', v: '<b>Integridade.</b>' },
  { f: 'Um vazamento de senhas viola qual princípio?', v: '<b>Confidencialidade.</b>' },
  { f: 'Qual a diferença entre autenticidade e não repúdio?', v: '<b>Autenticidade</b> é provar quem é. <b>Não repúdio</b> é não poder negar depois que fez.' },
  { f: 'Diferencie ameaça de vulnerabilidade.', v: '<b>Vulnerabilidade</b> é a fraqueza interna (você conserta). <b>Ameaça</b> é o agente externo (você não controla).' },
  { f: 'Qual a fórmula do risco?', v: '<b>Risco = probabilidade × impacto</b>' },
  { f: 'Quais as quatro respostas possíveis a um risco?', v: '<b>Mitigar, transferir, aceitar e evitar.</b>' },
  { f: 'Criptografia simétrica: quantas chaves e qual o problema?', v: '<b>Uma só</b>, compartilhada. É rápida, mas o problema é <b>distribuir a chave</b> com segurança. Ex: AES.' },
  { f: 'Criptografia assimétrica: como funciona?', v: 'Um <b>par de chaves</b>, pública e privada. O que uma fecha, só a outra abre. Ex: RSA.' },
  { f: 'Para enviar com SIGILO, uso qual chave?', v: 'A chave <b>pública do destinatário</b>: só ele, com a privada dele, consegue abrir.' },
  { f: 'Para ASSINAR, uso qual chave?', v: 'A <b>minha chave privada</b>: qualquer um confere com a minha pública que fui eu.' },
  { f: 'O que é hash e o que ele garante?', v: 'Função de <b>via única</b> (não tem volta), que gera um resumo de tamanho fixo. Garante <b>integridade</b>. Ex: SHA-256.' },
  { f: 'A assinatura digital garante confidencialidade?', v: '<b>NÃO.</b> Garante autenticidade, integridade e não repúdio, mas o documento continua legível para todos.' },
  { f: 'O que é um certificado digital?', v: 'Documento emitido por uma <b>Autoridade Certificadora</b> que atesta a quem pertence determinada chave pública.' },
  { f: 'Quais são os três fatores de autenticação?', v: 'Algo que você <b>sabe</b> (senha), algo que você <b>tem</b> (token) e algo que você <b>é</b> (biometria).' },
  { f: 'Qual a diferença entre autenticação e autorização?', v: '<b>Autenticação</b> é provar quem você é. <b>Autorização</b> é o que você pode fazer depois. Autenticar vem primeiro.' },
  { f: 'O que é o princípio do menor privilégio?', v: 'Cada usuário recebe <b>exatamente o acesso necessário</b> para o trabalho dele, nada além.' },
  { f: 'DAC, MAC e RBAC: quem decide o acesso em cada um?', v: '<b>DAC</b>: o dono do arquivo. <b>MAC</b>: o sistema, por rótulos. <b>RBAC</b>: o papel/cargo da pessoa.' },
  { f: 'Vírus × worm: qual a diferença?', v: '<b>Vírus precisa de hospedeiro</b> e de alguém executar. <b>Worm se propaga sozinho</b> pela rede.' },
  { f: 'O que caracteriza um trojan?', v: 'Se <b>disfarça</b> de programa legítimo. E, diferente de vírus e worm, <b>não se replica</b>.' },
  { f: 'O que é ransomware e qual a única defesa real?', v: 'Criptografa seus dados e exige resgate. A defesa real é <b>backup</b>.' },
  { f: 'O que é um rootkit?', v: 'Malware que <b>esconde a invasão do próprio SO</b>, sendo muito difícil de detectar.' },
  { f: 'O que é vírus de boot?', v: 'O que ataca o setor de inicialização e roda <b>antes do sistema operacional carregar</b>.' },
  { f: 'O que é vírus de macro?', v: 'O que vive em documentos de <b>Word, Excel e PowerPoint</b>.' },
  { f: 'Qual a diferença entre DoS e DDoS?', v: 'O <b>DDoS</b> é distribuído: vem de <b>várias máquinas</b> ao mesmo tempo, geralmente uma botnet.' },
  { f: 'Como se previne SQL Injection?', v: 'Com <b>prepared statements</b> e <b>validação de entrada</b>. Antivírus não resolve.' },
  { f: 'IDS × IPS: qual a diferença?', v: '<b>IDS detecta</b> e avisa (passivo). <b>IPS detecta e bloqueia</b> (ativo).' },
  { f: 'O que diz a regra 3-2-1 de backup?', v: '<b>3</b> cópias, em <b>2</b> mídias diferentes, com <b>1</b> fora do local.' },
  { f: 'Backup incremental × diferencial?', v: '<b>Incremental</b>: o que mudou desde o <b>último backup de qualquer tipo</b>. <b>Diferencial</b>: o que mudou desde o último <b>completo</b>.' },
  { f: 'Qual a palavra que separa hacker de cracker?', v: '<b>Autorização.</b> Hacker age de forma ética e autorizada; cracker, não.' },
  { f: 'Na LGPD, o que é dado sensível?', v: 'Origem racial, religião, opinião política, saúde, biometria e vida sexual. Tem <b>proteção reforçada</b>.' },
  { f: 'Qual é o elo mais fraco da segurança?', v: '<b>A pessoa.</b> Por isso engenharia social e phishing funcionam mesmo com boa tecnologia.' }
]
};

const QUESTOES = {

modelagem: [
  { q: 'Em qual nível de modelagem aparecem pela primeira vez as tabelas, chaves primárias e estrangeiras?',
    ops: ['Conceitual', 'Lógico', 'Físico', 'Em nenhum, isso é só no SGBD'], certa: 1,
    porque: 'O conceitual trabalha com entidades e relacionamentos, sem tecnologia. O <b>lógico</b> traduz isso em tabelas e chaves, ainda sem escolher o SGBD. O físico só acrescenta tipos, tamanhos e índices.' },
  { q: 'Um aluno pode cursar várias disciplinas e uma disciplina tem vários alunos. Como isso é implementado no modelo relacional?',
    ops: ['FK na tabela alunos', 'FK na tabela disciplinas', 'Uma tabela associativa com as duas FKs', 'Um campo multivalorado em alunos'], certa: 2,
    porque: 'É um relacionamento <b>N:N</b>. Como uma coluna guarda um valor só, nenhum dos dois lados aguenta a FK, cria-se uma <b>tabela associativa</b>, que transforma o N:N em dois relacionamentos 1:N.' },
  { q: 'Em um relacionamento 1:N entre CURSO e ALUNO, a chave estrangeira fica:',
    ops: ['Na tabela do lado 1 (cursos)', 'Na tabela do lado N (alunos)', 'Nas duas tabelas', 'Em uma terceira tabela'], certa: 1,
    porque: 'A regra é fixa: <b>a FK mora no lado N</b>. Cada aluno pertence a um curso, então cabe um único curso_id na linha do aluno. O contrário não caberia.' },
  { q: 'Sobre chave primária e chave estrangeira, é correto afirmar:',
    ops: ['As duas aceitam NULL', 'Nenhuma das duas aceita NULL', 'A PK aceita NULL, a FK não', 'A FK aceita NULL, a PK não'], certa: 3,
    porque: 'A <b>PK nunca aceita NULL</b>: ela identifica a linha. A <b>FK aceita</b>, e isso significa "ainda não tem relacionamento", como um aluno que ainda não escolheu curso.' },
  { q: 'Uma tabela tem PK composta (aluno_id + disciplina_id) e uma coluna nome_aluno, que depende apenas de aluno_id. Qual forma normal está sendo violada?',
    ops: ['1FN', '2FN', '3FN', 'Nenhuma'], certa: 1,
    porque: 'nome_aluno depende de <b>parte</b> da chave composta, não dela inteira. Isso é <b>dependência parcial</b>, que a <b>2FN</b> proíbe.' },
  { q: 'Uma tabela tem PK "id" e as colunas cep e cidade, sendo que cidade é determinada pelo cep. Qual forma normal está sendo violada?',
    ops: ['1FN', '2FN', '3FN', 'Nenhuma'], certa: 2,
    porque: 'cidade depende de cep, que é <b>outro campo não-chave</b>. Isso é <b>dependência transitiva</b>, proibida pela <b>3FN</b>. Não é 2FN porque a chave nem é composta.' },
  { q: 'Uma tabela cuja chave primária é uma única coluna e que está na 1FN:',
    ops: ['Pode violar a 2FN', 'Está automaticamente na 2FN', 'Está automaticamente na 3FN', 'Não pode ter FK'], certa: 1,
    porque: 'A 2FN trata de <b>dependência parcial da chave</b>, e só existe pedaço de chave quando a chave é composta. Com PK de uma coluna só, estar em 1FN já garante a 2FN. A 3FN ainda pode ser violada.' },
  { q: 'Um campo "telefones" que guarda "9999-1111 / 9999-2222" na mesma célula viola:',
    ops: ['1FN', '2FN', '3FN', 'Nenhuma, desde que separado por barra'], certa: 0,
    porque: 'A <b>1FN</b> exige valores <b>atômicos</b>: um valor por campo. Dois telefones na mesma célula quebram isso, e a solução é criar uma tabela de telefones.' },
  { q: 'Qual das anomalias descreve: "não consigo cadastrar um curso novo porque ainda não há aluno matriculado nele"?',
    ops: ['Anomalia de inserção', 'Anomalia de atualização', 'Anomalia de exclusão', 'Anomalia de integridade'], certa: 0,
    porque: 'É a <b>anomalia de inserção</b>: a estrutura mal normalizada exige um dado que ainda não existe para gravar outro que já existe.' },
  { q: 'Uma entidade DEPENDENTE que só existe vinculada a FUNCIONÁRIO e cuja identificação depende dele é chamada de:',
    ops: ['Entidade associativa', 'Entidade fraca', 'Entidade especializada', 'Autorrelacionamento'], certa: 1,
    porque: '<b>Entidade fraca</b>: não existe sozinha e tem <b>chave parcial</b>, que só funciona somada à PK da entidade forte. No DER usa retângulo duplo.' },
  { q: 'No DER, a elipse representa:',
    ops: ['Entidade', 'Relacionamento', 'Atributo', 'Cardinalidade'], certa: 2,
    porque: 'Retângulo = entidade, losango = relacionamento, <b>elipse = atributo</b>.' },
  { q: 'O atributo "idade", que pode ser calculado a partir da data de nascimento, é classificado como:',
    ops: ['Composto', 'Multivalorado', 'Derivado', 'Identificador'], certa: 2,
    porque: '<b>Derivado</b>: obtém-se de outro atributo e normalmente não se armazena, justamente para não ficar desatualizado.' },
  { q: 'A garantia de que uma FK sempre aponta para uma linha existente na tabela referenciada chama-se:',
    ops: ['Integridade de domínio', 'Integridade de entidade', 'Integridade referencial', 'Normalização'], certa: 2,
    porque: '<b>Integridade referencial</b>. A de <i>entidade</i> é a regra da PK (única e não nula); a de <i>domínio</i> é o valor caber no tipo/regra da coluna.' },
  { q: 'Em uma tabela associativa MATRICULA(aluno_id, disciplina_id, nota), o campo "nota" é atributo de quê?',
    ops: ['Do aluno', 'Da disciplina', 'Do relacionamento entre os dois', 'É um erro de modelagem'], certa: 2,
    porque: 'A nota não pertence ao aluno (ele tem várias) nem à disciplina (ela tem várias): pertence <b>ao encontro dos dois</b>. Atributo de relacionamento é exatamente isso.' },
  { q: 'Qual afirmação sobre o modelo conceitual está CORRETA?',
    ops: ['Define os tipos de dados de cada coluna', 'Depende do SGBD escolhido', 'Representa entidades e relacionamentos sem considerar tecnologia', 'É criado depois do modelo físico'], certa: 2,
    porque: 'O conceitual é o mais abstrato: entidades, atributos e relacionamentos, <b>independente de tecnologia</b>. Tipos de dado e SGBD são assunto do físico.' },
  { q: 'Assinale a alternativa que apresenta uma chave candidata na tabela ALUNOS(id, cpf, email, nome):',
    ops: ['nome', 'cpf', 'Apenas id, porque é a PK', 'Nenhuma, pois só pode haver uma chave'], certa: 1,
    porque: 'Chave candidata é <b>qualquer coluna capaz de identificar unicamente</b> a linha. cpf serve (e email também). A escolhida vira PK; as outras viram <b>alternativas</b>.' }
],

sql: [
  { q: 'Qual comando pertence à DDL?',
    ops: ['INSERT', 'UPDATE', 'ALTER', 'SELECT'], certa: 2,
    porque: '<b>DDL</b> define estrutura: CREATE, <b>ALTER</b>, DROP, TRUNCATE. INSERT e UPDATE são DML; SELECT é DQL (ou DML, dependendo da banca).' },
  { q: 'Sobre DELETE e TRUNCATE, é correto afirmar:',
    ops: ['Ambos aceitam WHERE', 'DELETE é DDL e TRUNCATE é DML', 'TRUNCATE não aceita WHERE e é DDL', 'Ambos apagam a estrutura da tabela'], certa: 2,
    porque: '<b>TRUNCATE é DDL</b>, esvazia tudo de uma vez, <b>não aceita WHERE</b> e não é revertido por ROLLBACK. DELETE é DML, apaga linha a linha e aceita WHERE.' },
  { q: 'Qual consulta retorna corretamente os alunos que ainda não possuem curso?',
    ops: ['SELECT * FROM alunos WHERE curso_id = NULL', 'SELECT * FROM alunos WHERE curso_id IS NULL', 'SELECT * FROM alunos WHERE curso_id = 0', 'SELECT * FROM alunos WHERE curso_id <> curso_id'], certa: 1,
    porque: 'NULL é <b>ausência de valor</b> e não se compara com <code>=</code>. A comparação não dá erro, simplesmente nunca é verdadeira. O correto é <b>IS NULL</b>.' },
  { q: 'Qual a diferença entre WHERE e HAVING?',
    ops: ['Não há diferença', 'WHERE filtra grupos e HAVING filtra linhas', 'WHERE filtra linhas antes do agrupamento e HAVING filtra grupos depois', 'HAVING só funciona com JOIN'], certa: 2,
    porque: 'Pela ordem de execução, <b>WHERE roda antes do GROUP BY</b> (filtra linha) e <b>HAVING roda depois</b> (filtra grupo). Por isso agregação só cabe no HAVING.' },
  { q: 'Por que a consulta "SELECT nome, AVG(nota) FROM matriculas" sem GROUP BY costuma dar erro?',
    ops: ['AVG não existe em SQL', 'nome não está em função de agregação nem no GROUP BY', 'Falta o WHERE', 'AVG só funciona com GROUP BY'], certa: 1,
    porque: 'AVG resume tudo em <b>uma linha</b>, mas "nome" tem vários valores. O banco não sabe qual escolher. Regra: coluna fora de agregação precisa estar no <b>GROUP BY</b>.' },
  { q: 'Você quer listar TODOS os alunos, inclusive os que não estão matriculados em nenhuma disciplina. Qual JOIN usar?',
    ops: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'Nenhum, é preciso duas consultas'], certa: 1,
    porque: 'A expressão <b>"inclusive os que não"</b> é a assinatura do <b>LEFT JOIN</b>: traz tudo da tabela da esquerda, tendo par ou não, preenchendo o resto com NULL.' },
  { q: 'Qual consulta lista os alunos SEM nenhuma matrícula?',
    ops: ['SELECT a.nome FROM alunos a JOIN matriculas m ON a.id = m.aluno_id WHERE m.id IS NULL', 'SELECT a.nome FROM alunos a LEFT JOIN matriculas m ON a.id = m.aluno_id WHERE m.id IS NULL', 'SELECT a.nome FROM alunos a WHERE a.id NOT IN (SELECT * FROM matriculas)', 'SELECT a.nome FROM alunos a, matriculas m WHERE a.id <> m.aluno_id'], certa: 1,
    porque: 'O padrão é <b>LEFT JOIN + IS NULL</b>: o LEFT traz todos os alunos, e quem não tem par fica com as colunas da direita nulas. Com INNER JOIN essas linhas nem apareceriam.' },
  { q: 'O que COUNT(*) faz de diferente de COUNT(nota)?',
    ops: ['Nada, são equivalentes', 'COUNT(*) ignora NULL e COUNT(nota) não', 'COUNT(*) conta todas as linhas e COUNT(nota) ignora os NULL', 'COUNT(*) só funciona com GROUP BY'], certa: 2,
    porque: '<b>COUNT(*) conta linhas</b>, com ou sem NULL. <b>COUNT(coluna) ignora os NULL</b> daquela coluna. É a diferença mais cobrada sobre agregação.' },
  { q: 'A cláusula LIKE \'%ana%\' retorna nomes que:',
    ops: ['Começam com ana', 'Terminam com ana', 'Contêm ana em qualquer posição', 'Têm exatamente três letras'], certa: 2,
    porque: '<b>%</b> representa qualquer quantidade de caracteres. Com % dos dois lados, basta que "ana" apareça <b>em qualquer posição</b>.' },
  { q: 'Qual é a ordem lógica de execução de um SELECT?',
    ops: ['SELECT → FROM → WHERE → GROUP BY → ORDER BY', 'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY', 'FROM → SELECT → WHERE → ORDER BY → GROUP BY', 'WHERE → FROM → SELECT → GROUP BY → HAVING'], certa: 1,
    porque: 'O banco começa pelo <b>FROM</b> e o <b>SELECT é quase o último</b>. É isso que explica por que um apelido criado no SELECT funciona no ORDER BY mas não no WHERE.' },
  { q: 'Qual restrição garante que o valor não se repita, mas permite um NULL?',
    ops: ['PRIMARY KEY', 'NOT NULL', 'UNIQUE', 'CHECK'], certa: 2,
    porque: '<b>UNIQUE</b> impede repetição mas aceita NULL. A PRIMARY KEY impede as duas coisas, é, na prática, UNIQUE + NOT NULL.' },
  { q: 'Para armazenar valores monetários, o tipo recomendado é:',
    ops: ['FLOAT', 'REAL', 'DECIMAL', 'DOUBLE'], certa: 2,
    porque: 'FLOAT, REAL e DOUBLE são tipos <b>aproximados</b> e acumulam erro de arredondamento. <b>DECIMAL</b> é exato, e por isso é o correto para dinheiro.' },
  { q: 'Qual é a sintaxe correta?',
    ops: ['UPDATE alunos WHERE id = 1 SET cidade = \'Recife\'', 'UPDATE alunos SET cidade = \'Recife\' WHERE id = 1', 'UPDATE SET cidade = \'Recife\' FROM alunos WHERE id = 1', 'UPDATE alunos SET WHERE id = 1 cidade = \'Recife\''], certa: 1,
    porque: 'A ordem é fixa: <b>UPDATE tabela SET coluna = valor WHERE condição</b>. O SET sempre vem antes do WHERE.' },
  { q: 'BETWEEN 7 AND 9 aplicado à coluna nota inclui os valores 7 e 9?',
    ops: ['Não inclui nenhum dos dois', 'Inclui só o 7', 'Inclui só o 9', 'Inclui os dois'], certa: 3,
    porque: '<b>BETWEEN é inclusivo nas duas pontas</b>. Equivale a <code>nota >= 7 AND nota <= 9</code>.' },
  { q: 'Para atravessar um relacionamento N:N entre alunos e disciplinas, quantos JOINs são necessários?',
    ops: ['Nenhum', 'Um', 'Dois', 'Três'], certa: 2,
    porque: '<b>Dois</b>: de alunos até a tabela associativa (matriculas) e desta até disciplinas. A tabela do meio é obrigatória no caminho.' },
  { q: 'Uma subconsulta que retorna vários valores deve ser usada com:',
    ops: ['=', 'IN', 'LIKE', 'BETWEEN'], certa: 1,
    porque: 'O operador <code>=</code> compara com <b>um</b> valor e gera erro se vier mais de um. Para lista, o correto é <b>IN</b>.' },
  { q: 'O que acontece ao executar "DELETE FROM alunos;" sem WHERE?',
    ops: ['Dá erro de sintaxe', 'Apaga apenas a primeira linha', 'Apaga todas as linhas da tabela', 'Apaga a tabela inteira, inclusive a estrutura'], certa: 2,
    porque: 'Sem WHERE o comando vale para <b>todas as linhas</b>. A estrutura permanece (para apagá-la seria DROP). Como é DML, ainda daria para reverter com ROLLBACK dentro de uma transação.' }
],

so: [
  { q: 'Qual a principal diferença entre processo e thread?',
    ops: ['Thread é mais lenta que processo', 'Threads do mesmo processo compartilham memória; processos são isolados', 'Processo não pode ter mais de uma thread', 'Thread não tem contador de programa'], certa: 1,
    porque: 'Processos têm <b>espaço de endereçamento isolado</b>. Threads do mesmo processo <b>compartilham memória</b>: daí serem rápidas de criar e comunicar, e daí também a condição de corrida.' },
  { q: 'O que uma thread possui exclusivamente?',
    ops: ['Código e dados globais', 'Arquivos abertos', 'Pilha, registradores e contador de programa', 'Espaço de endereçamento próprio'], certa: 2,
    porque: 'Cada thread tem sua <b>pilha, registradores e contador de programa</b>. Código, dados globais e arquivos abertos são compartilhados com as irmãs.' },
  { q: 'Um processo que estava Executando e pediu leitura de disco vai para qual estado?',
    ops: ['Pronto', 'Bloqueado', 'Terminado', 'Novo'], certa: 1,
    porque: 'Ele vai para <b>Bloqueado</b>, esperando a E/S. Não adianta dar CPU a ele nesse momento, o que ele espera não depende de processador.' },
  { q: 'Quando termina a E/S que um processo bloqueado aguardava, ele vai para:',
    ops: ['Executando, imediatamente', 'Pronto', 'Novo', 'Terminado'], certa: 1,
    porque: 'Ele volta para a <b>fila de Pronto</b> e espera o escalonador escolhê-lo. A transição <i>Bloqueado → Executando</i> <b>não existe</b>: essa é a pegadinha mais comum da matéria.' },
  { q: 'Scheduler e dispatcher se distinguem porque:',
    ops: ['São sinônimos', 'O scheduler escolhe o processo e o dispatcher faz a troca de contexto', 'O dispatcher escolhe e o scheduler executa', 'O dispatcher só atua em sistemas preemptivos'], certa: 1,
    porque: '<b>Scheduler decide</b> quem é o próximo; <b>dispatcher executa a decisão</b>, fazendo a troca de contexto e entregando a CPU.' },
  { q: 'Processos: P1 (chegada 0, execução 5) e P2 (chegada 1, execução 3). Usando FCFS, qual o tempo médio de espera?',
    ops: ['0', '2', '3', '4'], certa: 1,
    porque: 'No FCFS: P1 roda de 0 a 5, P2 de 5 a 8. Espera de P1 = 0. Espera de P2 = 5 − 1 = 4. Média = (0 + 4) ÷ 2 = <b>2</b>.' },
  { q: 'Qual algoritmo garante, comprovadamente, o menor tempo médio de espera?',
    ops: ['FCFS', 'SJF', 'Round Robin', 'Prioridade'], certa: 1,
    porque: 'O <b>SJF é ótimo</b> para tempo médio de espera. Sua limitação prática é exigir conhecer a duração dos processos de antemão, o que só se consegue por estimativa.' },
  { q: 'O "efeito comboio" é problema característico de qual algoritmo?',
    ops: ['SJF', 'Round Robin', 'FCFS', 'SRTF'], certa: 2,
    porque: 'No <b>FCFS</b> um processo longo na frente segura todos os curtos atrás, como caminhão em estrada de pista simples.' },
  { q: 'Starvation em escalonamento por prioridade é resolvida por:',
    ops: ['Aumentar o quantum', 'Aging', 'Tornar o algoritmo não preemptivo', 'Algoritmo do banqueiro'], certa: 1,
    porque: '<b>Aging</b> aumenta gradualmente a prioridade de quem espera, garantindo que mesmo o processo menos prioritário eventualmente execute.' },
  { q: 'Se o quantum do Round Robin for muito grande, ele tende a se comportar como:',
    ops: ['SJF', 'FCFS', 'SRTF', 'Prioridade'], certa: 1,
    porque: 'Com quantum grande demais, cada processo termina dentro da própria fatia e ninguém é interrompido, o comportamento vira <b>FCFS</b>.' },
  { q: 'Quantas das condições de Coffman precisam estar presentes para haver deadlock?',
    ops: ['Pelo menos uma', 'Pelo menos duas', 'Três', 'As quatro simultaneamente'], certa: 3,
    porque: 'As <b>quatro ao mesmo tempo</b>: exclusão mútua, posse e espera, não preempção e espera circular. Quebrar qualquer uma impede o deadlock, é nisso que se baseia a prevenção.' },
  { q: 'O algoritmo do banqueiro é uma estratégia de:',
    ops: ['Prevenção', 'Evitação (impedimento)', 'Detecção', 'Recuperação'], certa: 1,
    porque: 'Ele é de <b>evitação</b>: permite que as condições existam, mas analisa cada pedido e só concede se o sistema permanecer em <b>estado seguro</b>.' },
  { q: 'Qual a diferença entre deadlock e starvation?',
    ops: ['São a mesma coisa', 'No deadlock os processos esperam permanentemente uns aos outros; na starvation o sistema avança mas um processo nunca é escolhido', 'Deadlock só ocorre com threads', 'Starvation trava o sistema inteiro'], certa: 1,
    porque: 'No <b>deadlock</b> o grupo inteiro está travado para sempre. Na <b>starvation</b> o sistema funciona normalmente, apenas aquele processo específico nunca ganha a vez.' },
  { q: 'Sobre mutex e semáforo, é correto afirmar:',
    ops: ['Mutex é um contador e semáforo é binário', 'Mutex tem dono: só quem travou pode destravar', 'Semáforo só permite uma thread por vez', 'São idênticos em qualquer situação'], certa: 1,
    porque: 'A distinção conceitual cobrada é a <b>posse</b>: o <b>mutex tem dono</b> (só quem fez lock faz unlock); o semáforo é um contador sem dono, e qualquer thread pode sinalizar.' },
  { q: 'As operações de um semáforo são:',
    ops: ['lock e unlock', 'wait (P) e signal (V)', 'open e close', 'push e pop'], certa: 1,
    porque: '<b>wait</b> (também P ou down) decrementa o contador e bloqueia se chegar a zero; <b>signal</b> (V ou up) incrementa e libera quem espera. lock/unlock são do mutex.' },
  { q: 'Condição de corrida acontece quando:',
    ops: ['Dois processos disputam a mesma CPU', 'O resultado depende da ordem de acesso de threads a um dado compartilhado', 'Um processo entra em deadlock', 'A memória acaba'], certa: 1,
    porque: 'A <b>race condition</b> é o resultado final variar conforme quem chegou primeiro ao dado compartilhado. A solução é proteger a <b>região crítica</b> com exclusão mútua.' },
  { q: 'Paginação e segmentação diferem porque:',
    ops: ['Paginação usa blocos de tamanho variável', 'Segmentação gera fragmentação interna', 'Paginação usa tamanho fixo e gera fragmentação interna; segmentação usa tamanho variável e gera fragmentação externa', 'Só a segmentação usa memória virtual'], certa: 2,
    porque: '<b>Paginação = fixo = fragmentação interna</b> (sobra dentro da página). <b>Segmentação = variável = fragmentação externa</b> (sobram buracos entre segmentos).' },
  { q: 'Thrashing ocorre quando:',
    ops: ['A CPU fica ociosa esperando E/S', 'O sistema passa mais tempo trocando páginas do que executando', 'Dois processos entram em deadlock', 'A tabela de páginas é corrompida'], certa: 1,
    porque: '<b>Thrashing</b> é o excesso de paginação: a memória está tão apertada que o sistema vive buscando páginas no disco e quase não executa código útil.' },
  { q: 'A organização física de um disco rígido é:',
    ops: ['Blocos, clusters e partições', 'Pratos, trilhas, setores e cilindros', 'Páginas, frames e segmentos', 'Nós, diretórios e inodes'], certa: 1,
    porque: '<b>Pratos → trilhas → setores → cilindros</b>. O setor é a menor unidade física; o cilindro é o conjunto de trilhas alinhadas verticalmente nos vários pratos.' },
  { q: 'Uma divisão por zero durante a execução de um programa gera:',
    ops: ['Uma interrupção de hardware', 'Um trap (exceção de software)', 'Um deadlock', 'Uma falta de página'], certa: 1,
    porque: '<b>Trap</b> vem do software, causado pelo próprio programa. <b>Interrupção</b> vem do hardware, quando um dispositivo externo avisa a CPU.' },
  { q: 'Na técnica de DMA:',
    ops: ['A CPU verifica constantemente se a operação terminou', 'O dispositivo transfere dados direto para a memória e só avisa a CPU no fim', 'A CPU copia byte a byte', 'Não há uso de interrupção'], certa: 1,
    porque: 'O <b>DMA</b> libera a CPU: o controlador faz a transferência direta para a memória e emite uma interrupção apenas ao concluir. É o oposto do polling, que desperdiça CPU perguntando.' }
],

seguranca: [
  { q: 'Um ataque de DDoS que derruba o site de uma empresa viola principalmente:',
    ops: ['Confidencialidade', 'Integridade', 'Disponibilidade', 'Não repúdio'], certa: 2,
    porque: 'DDoS não rouba nem altera dado: <b>impede o acesso</b>. Isso é violação de <b>disponibilidade</b>.' },
  { q: 'Um funcionário altera indevidamente o valor de uma nota fiscal no sistema. Qual princípio foi violado?',
    ops: ['Confidencialidade', 'Integridade', 'Disponibilidade', 'Legalidade'], certa: 1,
    porque: 'O dado foi <b>alterado indevidamente</b>: isso é <b>integridade</b>, garantida na prática por hash e assinatura digital.' },
  { q: 'A diferença entre ameaça e vulnerabilidade é:',
    ops: ['São sinônimos', 'Vulnerabilidade é a fraqueza do ativo; ameaça é o agente que pode explorá-la', 'Ameaça é interna e vulnerabilidade é externa', 'Vulnerabilidade só existe em software'], certa: 1,
    porque: '<b>Vulnerabilidade</b> é a janela destrancada (interna, você conserta). <b>Ameaça</b> é o ladrão (externa, você não controla). Inverter os dois é o erro mais cobrado.' },
  { q: 'Para enviar uma mensagem que SÓ o destinatário consiga ler, o remetente deve cifrar com:',
    ops: ['A chave privada do remetente', 'A chave pública do remetente', 'A chave pública do destinatário', 'A chave privada do destinatário'], certa: 2,
    porque: 'Cifrando com a <b>chave pública do destinatário</b>, apenas a privada dele abre, e só ele a possui. É o mecanismo de <b>sigilo</b>.' },
  { q: 'Na assinatura digital, o autor cifra o hash do documento com:',
    ops: ['A chave pública dele', 'A chave privada dele', 'A chave pública do destinatário', 'Uma chave simétrica'], certa: 1,
    porque: 'Com a <b>chave privada do autor</b>. Como só ele a possui, quem conseguir abrir com a pública dele tem prova de autoria, daí a <b>autenticidade e o não repúdio</b>.' },
  { q: 'A assinatura digital garante:',
    ops: ['Confidencialidade, integridade e disponibilidade', 'Autenticidade, integridade e não repúdio', 'Apenas confidencialidade', 'Apenas disponibilidade'], certa: 1,
    porque: 'Ela garante <b>autenticidade, integridade e não repúdio</b>, mas <b>não confidencialidade</b>: o documento continua legível para qualquer um. Pegadinha número um da matéria.' },
  { q: 'Sobre funções de hash, é correto afirmar:',
    ops: ['São reversíveis com a chave correta', 'São de via única e garantem integridade', 'Substituem a criptografia simétrica', 'Geram saída de tamanho variável'], certa: 1,
    porque: 'Hash é <b>via única</b>: não existe operação de volta. Gera resumo de <b>tamanho fixo</b> e serve para verificar <b>integridade</b>.' },
  { q: 'A principal desvantagem da criptografia simétrica é:',
    ops: ['A lentidão', 'A distribuição segura da chave', 'Não garantir integridade', 'Exigir certificado digital'], certa: 1,
    porque: 'Ela é justamente a <b>mais rápida</b>. O problema é entregar a chave única ao outro lado sem que seja interceptada, problema que a assimétrica resolve.' },
  { q: 'Qual a diferença entre vírus e worm?',
    ops: ['O vírus se propaga sozinho e o worm precisa de hospedeiro', 'O vírus precisa de hospedeiro e de execução; o worm se propaga sozinho pela rede', 'Ambos precisam de hospedeiro', 'O worm não causa danos'], certa: 1,
    porque: '<b>Vírus precisa de carona</b> (um arquivo hospedeiro) e de alguém executar. <b>Worm anda sozinho</b> pela rede, sem ninguém clicar em nada.' },
  { q: 'Um programa que se disfarça de software legítimo, mas NÃO se replica, é um:',
    ops: ['Vírus', 'Worm', 'Trojan', 'Rootkit'], certa: 2,
    porque: 'A marca do <b>cavalo de troia</b> é o disfarce somado à ausência de replicação, ele depende de você instalá-lo achando que é outra coisa.' },
  { q: 'Qual é a defesa mais eficaz contra ransomware?',
    ops: ['Antivírus atualizado', 'Firewall', 'Backup', 'VPN'], certa: 2,
    porque: 'Se os dados estão cifrados pelo criminoso, só o <b>backup</b> os traz de volta sem pagar resgate. As outras defesas ajudam a evitar a infecção, mas não recuperam nada.' },
  { q: 'Um vírus que ataca o setor de inicialização e roda antes do sistema operacional carregar é o vírus de:',
    ops: ['Macro', 'Boot', 'Memória', 'Código-fonte'], certa: 1,
    porque: 'O <b>vírus de boot</b> infecta o setor de inicialização e por isso é carregado <b>antes do SO</b>, o que dificulta muito sua remoção.' },
  { q: 'Autenticação de dois fatores exige:',
    ops: ['Duas senhas diferentes', 'Dois fatores de tipos diferentes, como senha e token', 'Uma senha longa', 'Senha e pergunta secreta'], certa: 1,
    porque: 'Precisa combinar <b>tipos diferentes</b> de prova: saber + ter, ou saber + ser. Senha e pergunta secreta são ambas "algo que você sabe", é o mesmo fator duas vezes.' },
  { q: 'O princípio do menor privilégio determina que:',
    ops: ['Todos tenham o mesmo acesso', 'O usuário receba apenas o acesso necessário às suas funções', 'Apenas o administrador tenha acesso', 'Os acessos sejam revisados anualmente'], certa: 1,
    porque: 'Cada um recebe <b>exatamente o necessário</b> para o próprio trabalho. Assim, uma conta comprometida causa o menor estrago possível.' },
  { q: 'No modelo RBAC, o acesso é concedido com base em:',
    ops: ['No dono do arquivo', 'Em rótulos de sigilo definidos pelo sistema', 'No papel ou cargo do usuário', 'No horário de acesso'], certa: 2,
    porque: '<b>RBAC</b> = Role-Based Access Control: a permissão vem do <b>papel</b>. DAC é o dono quem decide; MAC é o sistema, por rótulos.' },
  { q: 'A diferença entre IDS e IPS é que:',
    ops: ['O IDS bloqueia e o IPS apenas detecta', 'O IDS apenas detecta e alerta; o IPS detecta e bloqueia', 'São a mesma tecnologia', 'O IPS funciona apenas em rede sem fio'], certa: 1,
    porque: 'A sigla entrega: <b>D de detection</b> (passivo, só avisa) e <b>P de prevention</b> (ativo, bloqueia).' },
  { q: 'A regra 3-2-1 de backup estabelece:',
    ops: ['3 backups por dia, 2 por semana, 1 por mês', '3 cópias, em 2 mídias diferentes, com 1 fora do local', '3 servidores, 2 discos, 1 fita', '3 usuários com acesso, 2 administradores, 1 dono'], certa: 1,
    porque: '<b>3 cópias, 2 mídias, 1 externa</b>. A cópia fora do local é o que protege contra incêndio, enchente e ransomware que alcança a rede inteira.' },
  { q: 'SQL Injection é prevenida principalmente por:',
    ops: ['Antivírus atualizado', 'Prepared statements e validação de entrada', 'Firewall de rede', 'Criptografia do banco'], certa: 1,
    porque: 'O ataque explora a <b>montagem de comando com texto do usuário</b>. A defesa está no código: <b>prepared statements</b> e validação. Antivírus e firewall não enxergam isso.' },
  { q: 'A diferença entre hacker e cracker está em:',
    ops: ['No nível de conhecimento técnico', 'Na autorização e na finalidade ética da ação', 'No sistema operacional usado', 'No tipo de ferramenta'], certa: 1,
    porque: 'A habilidade pode ser a mesma. O que separa é agir <b>com autorização e finalidade ética</b> (hacker, white hat) ou não (cracker, black hat).' },
  { q: 'Segundo a LGPD, são dados sensíveis:',
    ops: ['Nome, CPF e endereço', 'Origem racial, religião, opinião política, saúde e biometria', 'Apenas dados bancários', 'Qualquer dado armazenado em nuvem'], certa: 1,
    porque: 'A lei define como <b>sensíveis</b> os dados capazes de gerar discriminação, raça, religião, opinião política, saúde, biometria, vida sexual, e lhes dá <b>proteção reforçada</b>. Nome e CPF são dados pessoais comuns.' },
  { q: 'Sobre a segurança dos sistemas operacionais, é correto afirmar:',
    ops: ['Linux é imune a vírus', 'macOS não possui vulnerabilidades', 'Windows é o maior alvo por sua popularidade, mas todos possuem vulnerabilidades', 'Apenas o Windows possui falhas'], certa: 2,
    porque: '<b>Nenhum SO é imune.</b> O Windows é mais atacado por ter a maior fatia de mercado. Alternativa que diga "imune" ou "sem vulnerabilidade" está sempre errada.' }
]
};
